name:               haspara
version:            0.0.0.7
github:             "telostat/haspara"
license:            MIT
author:             "Vehbi Sinan Tunalioglu"
maintainer:         "vst@vsthost.com"
copyright:          "Copyright (c) 2021-2022 Telostat Pte Ltd"

category:           Finance
synopsis:           A library providing definitions to work with monetary values.
description:        Please see the README on GitHub at <https://github.com/telostat/haspara#readme>

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.11 && < 5

library:
  source-dirs:      src
  ghc-options:
  - -Wall
  - -Wunused-packages
  dependencies:
  - aeson >=1.5.6.0 && <2.1
  - containers >=0.6.4.1 && <0.7
  - data-default >= 0.7 && <0.8
  - exceptions >=0.10.4 && <0.11
  - hashable >=1.3.0.0 && <1.4
  - megaparsec >=9.0.1 && <9.3
  - mtl >=2.2.2 && <2.3
  - refined >=0.6.3 && <0.7
  - safe-decimal >=0.2.1.0 && <0.3
  - scientific >=0.3.7.0 && <0.4
  - template-haskell >=2.16.0.0 && <2.18
  - text >=1.2.4.1 && <1.3
  - time >=1.9.3 && <1.10

tests:
  haspara-test:
    main:           test.hs
    source-dirs:    test
    ghc-options:
    - -Wall
    - -Wunused-packages
    - -threaded
    dependencies:
    - containers
    - data-default
    - haspara
    - hspec
    - time

  haspara-doctest:
    main:           doctest.hs
    source-dirs:    .
    ghc-options:
    - -threaded
    dependencies:
    - doctest
