name:               haspara
version:            0.0.0.2
github:             "telostat/haspara"
license:            MIT
author:             "Vehbi Sinan Tunalioglu"
maintainer:         "vst@vsthost.com"
copyright:          "Copyright (c) 2021-2022 Telostat Pte Ltd"

category:           Finance
synopsis:           A library providing definitions to work with monetary values.
description:        Please see the README on GitHub at <https://github.com/telostat/haspara#readme>

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.11 && < 5
- aeson
- containers
- deriving-aeson
- hashable
- megaparsec
- mtl
- refined
- safe-decimal
- scientific
- template-haskell
- text
- time

library:
  source-dirs:      src
  ghc-options:
  - -Wall
  - -Wunused-packages
  default-extensions:
  - OverloadedStrings

tests:
  haspara-doctest:
    main:           doctest.hs
    source-dirs:    test
    ghc-options:
    - -threaded
    dependencies:
    - haspara
    - doctest
