name: haspara
version: 0.0.0.8
github: "telostat/haspara"
license: MIT
author: "Vehbi Sinan Tunalioglu"
maintainer: "vst@vsthost.com"
copyright: "Copyright (c) 2021-2024 Telostat Pte Ltd"
category: Finance
synopsis: A library providing definitions to work with monetary values.
description: Please see the README on GitHub at <https://github.com/telostat/haspara#readme>

extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base >= 4.11 && < 5

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wunused-packages
  dependencies:
    - aeson >=1.5.6.0 && <2.3
    - containers >=0.6.4.1 && <0.7
    - data-default >= 0.7 && <0.8
    - exceptions >=0.10.4 && <0.11
    - hashable >=1.3.0.0 && <1.5
    - megaparsec >=9.0.1 && <9.6
    - mtl >=2.2.2 && <2.4
    - refined >=0.6.3 && <0.9
    - safe-decimal >=0.2.1.0 && <0.3
    - scientific >=0.3.7.0 && <0.4
    - template-haskell >=2.16.0.0 && <2.21
    - text >=1.2.4.1 && <2.2
    - time >=1.9.3 && <1.14

tests:
  haspara-test:
    main: Spec.hs
    source-dirs: test/spec
    ghc-options:
      - -Wall
      - -Wunused-packages
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - containers
      - data-default
      - haspara
      - hspec
      - time

  haspara-doctest:
    main: doctest.hs
    source-dirs: test/doctest
    ghc-options:
      - -Wall
      - -threaded
    dependencies:
      - haspara
      - doctest
